compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  babel-plugin-replace-import-extension@*:
    peerDependencies:
      "@babel/core": "*"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-4.9.4.cjs
