enableScripts: false

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnpm

packageExtensions:
  "@testing-library/jest-dom@*":
    peerDependencies:
      vitest: "*"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-4.13.0.cjs

npmMinimalAgeGate: "7d"
npmPreapprovedPackages:
  - "@wantedly/*"
  - "@wantedly_private/*"
