compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnpm

packageExtensions:
  babel-plugin-replace-import-extension@*:
    peerDependencies:
      "@babel/core": "*"
  "@testing-library/jest-dom@*":
    peerDependencies:
      "vitest": "*"
  "pretty-format@*":
    dependencies:
      react-is: "^19.0.0"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-4.9.4.cjs
