compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnpm

packageExtensions:
  "@testing-library/jest-dom@*":
    peerDependencies:
      "vitest": "*"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-4.9.4.cjs
