name: Release

on:
  push:
    branches:
      - master

permissions:
  # Required for OIDC (Trusted Publishing)
  id-token: write
  # Required to push release branches
  contents: write
  # # Required to create release Pull Requests
  # pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # To use a dedicated GITHUB_TOKEN and also
    # to pass the trusted publishing condition.
    environment: publish
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create Release Pull Request or prepare publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          commitMode: github-api
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
